name: 'Disconnect VPN'
description: 'Disconnect and kills VPN'
inputs:
  debug:
    required: false
    description: If debug is set to true then VPN logs will be uploaded to job artifacts
    default: "false"

runs:
  using: "composite"
  steps:

    - id: kill-vpn
      name: Kill vpn
      shell: bash
      run: |
        sudo killall openvpn

