name: Build Test and Lint

on:
  workflow_call:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
    secrets:
      registry_url:
        required: true
        description: Harbor registry url
      vpn_profile:
        required: true
        description: VPN Profile that is used to connect to private infra
      gh_personal_access_token:
        required: true
        description: Github token that can be used for building apps or adding comments to PR etc
      ssh_private_key:
        required: true
        description: Required private key to use ssh-agent for installing dependencies from github private repos.

jobs:
  build-and-test:
    name: Build test and lint application
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - id: vpn
        name: Setting up VPN
        uses: pypestream/github-workflows/.github/actions/start-vpn@master
        with:
          vpn_profile: ${{ secrets.vpn_profile }}
          registry_url: ${{ secrets.registry_url }}

      - id: check-vpn
        name: Checking VPN connection
        run: |
          IS_VPN_CONNECTED=${{ steps.vpn.outputs.IS_VPN_CONNECTED }}
          if [ ${IS_VPN_CONNECTED} -eq false ]; then
            echo "VPN is not connected so failing the job, please run this workflow with debug mode to see vpn logs in the artifacts"
            exit 1
          fi

      - id: repo
        run: |
          repo_name=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}')
          echo "::set-output name=REPO_NAME::$repo_name"
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.ssh_private_key }}

      - id: build-and-test
        name: Build test and lint application
        run: |
          make build image=${{ steps.repo.outputs.REPO_NAME }} version=latest github_token=${{ secrets.gh_personal_access_token }}
          make build-test image=${{ steps.repo.outputs.REPO_NAME }} version=latest github_token=${{ secrets.gh_personal_access_token }}
          make test image=${{ steps.repo.outputs.REPO_NAME }} version=latest
          make lint image=${{ steps.repo.outputs.REPO_NAME }} version=latest || true

      - id: vpn-disconnect
        name: Post RUN Stops VPN
        if: always()
        uses: pypestream/github-workflows/.github/actions/stop-vpn@master
        with:
          debug: ${{ inputs.debug }}
