name: Create Pull Request

on:
  workflow_call:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
      destination_branch:
        type: string
        default: main
        required: false
        description: Destination branch name defaults to `main`
      pr_template_file:
        type: string
        default: ""
        required: false
        description: PR template
      pr_label:
        type: string
        default: "Need Code Review"
        required: false
        description: Lables to add (comma separated list)
    secrets:
      gh_personal_access_token:
        required: true
        description: Github token that can be used for building apps or adding comments to PR etc

jobs:
    create-pr:
      runs-on: ubuntu-latest
      permissions:
          packages: write
          contents: read
      steps:
      - uses: actions/checkout@v2
      - id: extract_branch
        name: Get Branch Name
        shell: bash
        run:  echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ inputs.destination_branch }}
          github_token: ${{ secrets.gh_personal_access_token }}
          pr_title: " ${{ github.actor }} Merge ${{ steps.extract_branch.outputs.branch }} into ${{ inputs.destination_branch }}"
          pr_body: "${{ github.event.head_commit.message }}"
          pr_template: "${{ inputs.pr_template_file }}"
          pr_draft: false
          pr_allow_empty: false
          pr_label: ${{ inputs.pr_label }}
